# the variable "ansible_user" will be automatically picked up from the group_vars directory

kube_version: v1.35
kube_components_version: 1.35.0-1.1

cilium_version: v1.18.3
clusterPoolIPv4PodCIDRList: 20.0.0.0/8